spring.application.name=customercare
server.port=8080
# H2 Database & Console Config
spring.datasource.url=jdbc:h2:file:./data/customercaredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=123123
# Enable H2 Web Console (Accessible via http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
# secret key
app.jwt.secret=response-201-is-more-beautiful-than-i-love-you-in-the-backend-world-but-the-real-mystery-is-why-this-developer-is-still-not-employed-at-digitinary
# 1 hour in milliseconds
app.jwt.expiration-ms=604800000
# عشان نشوف اي log debug
logging.level.org.springframework.security=DEBUG

